// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUCCiR4AVZXNf6Z-eu4brLbGCzNfyd_Ww',
    appId: '1:696857958541:web:394409b0bf4518878b6ac4',
    messagingSenderId: '696857958541',
    projectId: 'chatappcli-1e8b9',
    authDomain: 'chatappcli-1e8b9.firebaseapp.com',
    storageBucket: 'chatappcli-1e8b9.appspot.com',
    measurementId: 'G-JLVHWBMF0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZk2GtSskp428AjDiReLAyRVqhaTnCRWo',
    appId: '1:696857958541:android:ff9221491d71b37f8b6ac4',
    messagingSenderId: '696857958541',
    projectId: 'chatappcli-1e8b9',
    storageBucket: 'chatappcli-1e8b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUhrdIqOufWVTQtzyZBNq0zpP_DXa-InA',
    appId: '1:696857958541:ios:325d3b96a6bc7b238b6ac4',
    messagingSenderId: '696857958541',
    projectId: 'chatappcli-1e8b9',
    storageBucket: 'chatappcli-1e8b9.appspot.com',
    iosClientId: '696857958541-r8672c714tve29h5ec788g714cr0qvk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppCli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUhrdIqOufWVTQtzyZBNq0zpP_DXa-InA',
    appId: '1:696857958541:ios:325d3b96a6bc7b238b6ac4',
    messagingSenderId: '696857958541',
    projectId: 'chatappcli-1e8b9',
    storageBucket: 'chatappcli-1e8b9.appspot.com',
    iosClientId: '696857958541-r8672c714tve29h5ec788g714cr0qvk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppCli',
  );
}
